---
title: "Tropical Conservation Biology"
---

Welcome to the course website for BIOL 335 Tropical Conservation Biology at MSUM, a.k.a. the "Costa Rica Course".

**If you think you may want to register for the course, email the instructor Dr. Chris Merkord chris.merkord@mnstate.edu now to get on the interest list.**

Content:

- [Course Overview]
- [Spring 2020 Course Information]
    - [Dates and Cost]
    - [Informational Meetings]
- [Course registration]
- [About the course]
    - [What is the trip like?]
    - [Where do we stay?]
    - [What kinds of activities will we do?]
    - [What kinds of plants and animals will we see?]

# Instructors

Chris Merkord chris.merkord@mnstate.edu
Brian Wisenden wisenden@mnstate.edu

# Course Overview

- Learn about tropical ecology in one of the most diverse places on Earth
- See different social and economic models for conservation biology
- Experience Costa Rican culture
- Build great friendships and make lasting memories
- Fulfill your LASC Goal 10 requirement

# Spring 2020 Course Information

## Dates and Cost

- Travel to Costa Rica Friday, March 6 to Tuesday, March 17.
- Class will meet weekly before the trip.
- Students will present at the [Student Academic Conference](https://www.mnstate.edu/sac/) April 21
- Approximate cost is $2,500 plus tuition
- **Student financial aid available for full cost**

## Informational Meetings

Informational meetings are held in the fall to give students a chance to hear more about the course and to ask questions of the instructors. Fall 2020 meetings:

- Wednesday, October 30, 11:00 AM in Langseth Hall 102
- Friday, November 1, 12:00 PM in Hagen Hall 113
- Monday, November 4, 1:00 PM in Langseth Hall 102

If you are unable to attend one of the informational meetings, or if you have any questions, please email one of the instructors.


# Course registration

- [Register](https://www.mnstate.edu/registrar/registration/) on the MSUM website beginning in October
- No prerequisites.
- Open to all majors.
- Tri-college students welcome.
- Permission is required to register for this course. Contact an instructor for permission.


# About the course

## What is the trip like?

Every trip is unique, but we guarantee you'll have an amazing experience. One of our past participants put together this video to give you an idea of what to expect on the trip.

<br />

<iframe width="560" height="315" src="https://www.youtube.com/embed/ylkJviot8Y4" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

<br />

And this is a slide show showing some of the places and things we'll see. Click the full screen button to enlarge.

<br />

<iframe src="https://mnscu-my.sharepoint.com/personal/su7849xi_minnstate_edu/_layouts/15/Doc.aspx?sourcedoc={af26d47f-c379-45ac-a165-ee124504defd}&amp;action=embedview&amp;wdAr=1.7777777777777777" width="610px" height="367px" frameborder="0">This is an embedded <a target="_blank" href="https://office.com">Microsoft Office</a> presentation, powered by <a target="_blank" href="https://office.com/webapps">Office Online</a>.</iframe>

<br />

## Where do we stay?

The trip is spent at three main locations:

1. The Monteverde and San Luis area in the mountains of eastern Guanacaste Province.
2. Cabo Blanco Absolute Reserve on the southern tip of the Nicoya Peninsula, Puntarenas Province.
3. Santa Rosa National Park in northwestern Guanacaste Province.


## What kinds of activities will we do?

The exact list of activities varies from year to year, but here are some examples of things done in the past:

- Tour coffee plantation and talk to owners
- Tour local sustainable businesses in San Luis
- Snorkeling (sea turtles, fish, lobster, etc.)
- Tidepooling (sea urchins, brittle stars, octopus, etc.)
- Swimming at waterfall
- Canopy tour on suspension bridges
- Sustainability tour of UGA campus
- Milking cows, feeding pigs, etc. on UGA campus
- Guided nature walks
- Guided birding walks (mornings)
- Night hikes to look for animals
- Explore La Casona, a historical fort in Santa Rosa
- Eating at local restaurants
- Exploring towns (e.g. Liberia, Bagaces)
- Ziplining (optional, extra fee)
- Horseback riding (optional, extra fee)

Here are some photos of some of these activities:

## What kinds of plants and animals will we see?

Photos of plants and animals seen on previous trips:

- [Birds](https://ebird.org/media/catalog?mediaType=Photo&searchField=user&includeUnconfirmed=true&userId=USER150509&regionCode=CR&sort=upload_date_desc), from eBird
- [Other plants and animals](https://www.inaturalist.org/projects/msum-costa-rica?tab=observations&subtab=grid), from iNaturalist